name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or whichever version you prefer

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --passWithNoTests

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: npm run build

    - name: Deploy to Hostinger
      run: |
        rsync -av --delete ./build/ u647644246@89.116.53.61:/path/to/public_html/
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
